//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrOCR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrOCR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;暗查&quot;:&quot;\tan\tzha&quot;,&quot;芥兰&quot;:&quot;\tgai\tlan&quot;,&quot;美发师&quot;:&quot;\tmei\tfa\tshi&quot;,&quot;阿里地区&quot;:&quot;\ta\tli\tdi\tqu&quot;,&quot;电子门&quot;:&quot;\tdian\tzi\tmen&quot;,&quot;聚合反应&quot;:&quot;\tju\the\tfan\tying&quot;,&quot;深省&quot;:&quot;\tshen\txing&quot;,&quot;刑讯逼供&quot;:&quot;\txing\txun\tbi\tgong&quot;,&quot;风镐&quot;:&quot;\tfeng\thao&quot;,&quot;寺观&quot;:&quot;\tsi\tguan&quot;,&quot;曾孙&quot;:&quot;\tzeng\tsun&quot;,&quot;曲尽其妙&quot;:&quot;\tqu\tjin\tqi\tmiao&quot;,&quot;家无担石&quot;:&quot;\tjia\twu\tdan\tshi&quot;,&quot;扫地以尽&quot;:&quot;\tsao\tdi\tyi\tjin&quot;,&quot;曾子&quot;:&quot;\tzeng\tzi&quot;,&quot;不足为虑&quot;:&quot;\tbu\tzu\twei\tlv&quot;,&quot;两边倒&quot;:&quot;\tliang\tbian\tdao&quot;,&quot;肖似&quot;:&quot;\txiao\tsi&quot;,&quot;故地重游&quot;:&quot;\tgu\tdi\tchong\tyou&quot;,&quot;感应圈&quot;:&quot;\tgan\tying\tquan&quot;,&quot;绞尽脑汁&quot;:&quot;\tjiao\tjin\tnao\tzhi&quot;,&quot;一定不易 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pinyin {
            get {
                return ResourceManager.GetString("pinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 头像 {
            get {
                object obj = ResourceManager.GetObject("头像", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 帮助 {
            get {
                object obj = ResourceManager.GetObject("帮助", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 快捷键_0 {
            get {
                object obj = ResourceManager.GetObject("快捷键_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 快捷键_1 {
            get {
                object obj = ResourceManager.GetObject("快捷键_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 语音按钮 {
            get {
                object obj = ResourceManager.GetObject("语音按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
